name: .NET Build and Release

on:
  push:
    tags:
      - '*'
  
permissions:
  contents: write
  
jobs:
  build-and-release:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        include:
          - os: windows-latest
            runtime: win-x64
          - os: ubuntu-latest
            runtime: linux-x64
          - os: ubuntu-latest
            runtime: linux-arm64

    steps:
      - uses: actions/checkout@v3

      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '8.0.x'

      - name: Restore dependencies
        run: dotnet restore ./ROBdk97.XmlDocToMd.csproj

      - name: Publish
        run: dotnet publish ./ROBdk97.XmlDocToMd.csproj -r ${{ matrix.runtime }} -c Release --no-restore -o publish/${{ matrix.runtime }}

      - name: Upload a Build Artifact
        uses: actions/upload-artifact@v3.1.3
        with:
          name: XmlDocToMd-${{ matrix.runtime }}
          path: publish/${{ matrix.runtime }}

  release:
    needs: build-and-release
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Download all artifacts
        uses: actions/download-artifact@v2
        with:
          path: release

      - name: Prepare Release Files
        run: |
          mkdir release_files
          find release -type f -exec mv {} release_files/ \;

      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          files: release_files/*
